MODULESDIR ?=			${PREFIX}/share/runawk

MODULES !=			cd ${.CURDIR}; echo *.awk gawk/*.awk

FILES =				${MODULES}
FILESDIR =			${MODULESDIR}
FILESNAME_gawk/ord.awk =	gawk/ord.awk

.include <mkc.files.mk>
