=head1 NAME

alt_getopt - parse command options

=head1 SYNOPSIS

 cmds=`alt_getopt opt1 action1 [opt2 action2...] -- "$@"`
 eval "$cmds"

=head1 DESCRIPTION

B<alt_getopt> is a command options parser. It conforms to POSIX
and supports long options, that is works the same way as
getopt_long(3) found in *BSD and GNU libc.

=head1 EXAMPLES

The following shell script accepts the options: -v (or
--verbose), -h (or --help), long option --fake without short synonym,
--len accepting argument, -o (or --output) accepting argument,
short options -f and -F without long synonyms etc. If option is
applied, appropriate shell command is executed.

 #!/bin/sh
 help () { echo 'help here'; }
 alt_getopt \
    v|verbose' 'verbose=1' \
    'h help'    help \
    'fake'      fake_flag=1 \
    '=len'      len= \
    '=o output' output= \
    '=m msg'    "msg=" \
    'V version' "echo 'alt_getopt-0-1-0'" \
    f           'flag=1' \
    F           'flag=' \
    =n          number= \
    -- "$@"
 echo "flag=$flag"
 echo "msg=$msg"

=head1 BUGS/FEEDBACK

Please send any comments, questions, bug reports etc. to me by e-mail
or register them at sourceforge project home.  Feature requests are
also welcomed.

=head1 HOME

L<http://sourceforge.net/projects/runawk>

=head1 SEE ALSO
L<getopt(3)>
L<getopt_long(3)>
