SCRIPTS       =	demo_alt_getopt demo_alt_getopt.sh demo_alt_getopt2.sh \
   demo_alt_join demo_backslash_in demo_basename demo_dirname demo_embed_str \
   demo_fieldwidths demo_ftrans demo_glob demo_glob2ere demo_has_prefix \
   demo_has_suffix demo_heapsort demo_heapsort2 demo_heapsort3 demo_heapsort4 \
   demo_ini demo_io demo_minmax demo_modinfo demo_multisub demo_power_getopt \
   demo_power_getopt2 demo_quicksort demo_quicksort2 demo_quicksort3 \
   demo_readfile demo_runcmd demo_shquote demo_splitre demo_str2regexp \
   demo_tmpfile demo_tokenre demo_tokenre2 demo_tokenre3 demo_tokenre4 \
   demo_trim demo_trim_in demo_tsv

FILES       =	demo_backslash_in.in demo_fieldwidths.in demo_has_prefix.in \
   demo_has_suffix.in demo_heapsort.in demo_heapsort3.in demo_heapsort4.in \
   demo_ini.in demo_readfile.in demo_shquote.in demo_tokenre.in \
   demo_tokenre2.in demo_tokenre3.in demo_trim.in demo_tsv.in

FILESDIR    =	${EGDIR}
SCRIPTSDIR  =	${EGDIR}

.include <mkc.files.mk>
